import day4_calculator as calcu

sum = calcu.add(1, 2)
difference = calcu.subtract(100, 8)
product = calcu.multiply(20, 60)
quotient = calcu.divide(4, 2)
remainder = calcu.modulo(9, 3)
summation = calcu.summation([x for x in range(6)])
floor_division = calcu.floor_division(5, 7)
radius = calcu.radius(25)
area = calcu.area(45, 24)
exponent = calcu.exponent(2, 3)
factorial = calcu.factorial(9)
circumference = calcu.circumference(42)
square_root = calcu.square_root(5)
volume = calcu.volume(4, 5, 6)
volume_of_cylinder = calcu.volume_of_cylinder(45)
area_of_circle = calcu.area_of_circle(55)
speed = calcu.speed(34, 5)

print(sum)
print(difference)
print(product)
print(quotient)
print(remainder)
print(summation)
print(floor_division)
print(radius)
print(area)
print(factorial)
print(circumference)
print(square_root)
print(volume)
print(volume_of_cylinder)
print(area_of_circle)
print(speed)
